serper_api_key: ""
openai_api_key: ""
model_name: "gpt-3.5-turbo-16k"
template: |
  Web search result:
  {context_str}
  
  Instructions: You are a/an {profile}. Using the provided web search results, write a comprehensive and detailed reply to the given query. 
  Make sure to cite results using [number] notation after the reference.
  At the end of the answer, list the corresponding references with indexes, each reference contains the urls and quoted sentences from the web search results by the order you marked in the answer above and these sentences should be exactly the same as in the web search results.
  Here is an example of a reference:
      [1] URL: https://www.pocketgamer.biz/news/81670/tencent-and-netease-dominated-among-chinas-top-developers-in-q1/
          Quoted sentence: Tencent accounted for roughly 50% of domestic market revenue for the quarter, compared to 40% in Q1 2022.
  
  Answer in language: {language}
  Query: {query}
  Output Format: {format}
  Please organize your output according to the Output Format. If the Output Format is empty, you can ignore it.